### ISSUE TITLE
poolBotMsg is not defined

### ISSUE THREAD

**Issue by tenpin784** [alloyproject/alloy-pool_nodejs#7]
Brand new install of OS, and deployed using the deploy script.

All node functions constantly restart, with the following error:

```
2018-03-23 20:18 +00:00: ReferenceError: poolBotMsg is not defined
    at module.exports (/home/jbarbieri/nodejs-pool/lib/support.js:202:21)
    at Object.<anonymous> (/home/jbarbieri/nodejs-pool/init.js:10:45)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Object.<anonymous> (/home/jbarbieri/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

Not sure where to start looking...

**Comment by ghost** [comment]
Nobody with idea here? Would be very nice to get this feature working :)

**Comment by ghost** [comment]
Just have to define poolBotMsg. Had a little dig in to it and the fix is easy enough. I can add a pull request for it.

**Comment by alexmateescu** [comment]
something was missing in a file. all fixed now
